{{- if .Values.openshift }}
{{- $labels := (include "actions-runner-controller.labels" .) }}
{{- $ServiceAccountName := $.Values.runnerServiceAccount.name}}
{{- range .Values.runnerNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:{{ $ServiceAccountName }}
  labels:
    {{- $labels | nindent 4 }} 
  {{- with $.Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }} 
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:{{ $ServiceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ $ServiceAccountName }}
  namespace: {{ . }}
{{- end }}
{{- end }}
