{{- if .Values.openshift }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:{{ .Values.runnerServiceAccount.name }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }} 
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{  .Values.securityContextConstraint.name }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}
