{{- if .Values.openshift }}
{{- $labels := (include "actions-runner-controller.labels" . )}}
{{- range .Values.runnerNamespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.runnerServiceAccount.name }}
  namespace: {{ . }}
  labels:
    {{- $labels | nindent 4 }} 
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
