# permissions for end users to edit actionsrunnercontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actionsrunnercontroller-editor-role
rules:
- apiGroups:
  - charts.example.com
  resources:
  - actionsrunnercontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.example.com
  resources:
  - actionsrunnercontrollers/status
  verbs:
  - get
