- apiGroups:
    - ''
  resources:
    - namespaces
  verbs:
    - get
- apiGroups:
    - ''
  resources:
    - secrets
  verbs:
    - '*'
- apiGroups:
    - ''
  resources:
    - events
  verbs:
    - create
- apiGroups:
    - github-practice.boxboat.com
  resources:
    - actionsrunnercontrollers
    - actionsrunnercontrollers/status
    - actionsrunnercontrollers/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ''
  resources:
    - pods
    - services
    - services/finalizers
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - '*'
- apiGroups:
    - cert-manager.io
  resources:
    - certificates
    - issuers
  verbs:
    - '*'
