apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  # We need to get namespaces so the operator can read namespaces to ensure they exist
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  # We need to manage Helm release secrets
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
  # We need to create events on CRs about things happening during reconciliation
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  ##
  ## Rules for github-practice.boxboat.com/v1alpha1, Kind: ActionsRunnerController
  ##
  - apiGroups:
      - github-practice.boxboat.com
    resources:
      - actionsrunnercontrollers
      - actionsrunnercontrollers/status
      - actionsrunnercontrollers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - issuers
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - roles
      - rolebindings
    verbs:
      - '*'
#+kubebuilder:scaffold:rules
