apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: github-arc-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: helm based operator for github actions runner controller
  displayName: github-arc-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - github
  - actions
  - boxboat
  - ibm
  - self-hosted
  - runners
  links:
  - name: Github Arc Operator
    url: https://github-arc-operator.domain
  maintainers:
  - email: Michael.McMullen@ibm.com
    name: mbmcmullen27
  maturity: alpha
  provider:
    name: boxboat-github-practice
    url: https://github.com/boxboat-github-practice
  version: 0.0.0
