apiVersion: github-practice.boxboat.com/v1alpha1
kind: ActionsRunnerController
metadata:
  name: actionsrunnercontroller-sample-2
  namespace: arc-controllers
spec:
  leaderElectionId: 2
  authSecret:
    name: ghauth
  scope:
    singleNamespace: true
    watchNamespace: test2
