apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: ghrunners-1
spec:
  replicas: 1
  template:
    spec:
      repository: boxboat-github-practice/github-arc-operator
