name: Build and Push OLM Bundle Image

on:
  push:
    branches:
      - main
    paths-ignore: 
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:
    
jobs:
  container:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Docker Build
      shell: bash
      run: |
        export IMG=ghcr.io/${GITHUB_REPOSITORY,,}:bundle-$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
        make bundle bundle-build
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Publish
      shell: bash
      run: |
        export IMG=ghcr.io/${GITHUB_REPOSITORY,,}:bundle-$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
        make bundle-push