name: Build and Push Images

on:
  push:
    tags: 
      - '**' 
    paths-ignore: 
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:
    
jobs:
  container:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
    - name: Set Version
      run: |
        TAG=${GITHUB_REF#refs/*/}
        if [[ $GITHUB_REF_TYPE != "tag" ]]; then
          VERSION=$(git tag -l -n1 --format="%(refname:strip=2)")
          VERSION=$(awk -F. '/[0-9]+\./{$NF++;print}' OFS=. <<< "$TAG")
          TAG=experimental
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "VERSION=$TAG" >> $GITHUB_ENV
        fi
        echo "IMG=ghcr.io/${GITHUB_REPOSITORY,,}:$TAG" >> $GITHUB_ENV
        echo "BUNDLE_IMG=ghcr.io/${GITHUB_REPOSITORY,,}:$TAG" >> $GITHUB_ENV
    - name: Install operator-sdk
      run: |
        export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
        export OS=$(uname | awk '{print tolower($0)}')
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.26.0
        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
        chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk
    - name: Build
      shell: bash
      run: |
        make bundle bundle-build docker-build
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      shell: bash
      run: |
        make docker-push bundle-push
    - name: list images
      shell: bash
      run: |
        docker images

