name: Build and Push Images

on:
  push:
    tags: 
      - '**' 
    paths-ignore: 
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:
  workflow_call: 
    inputs:
      tag:
        required: false
        type: string
    
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set Version
      run: |
        if [[ $GITHUB_REF_TYPE == "tag" ]]; then
          TAG=${GITHUB_REF#refs/*/}
          echo "VERSION=$TAG" >> $GITHUB_ENV
        elif [[ ! -z ${{ inputs.tag }} ]]; then
          TAG=${{ inputs.tag }}
          echo "VERSION=${{ inputs.tag }}" >> $GITHUB_ENV
        else
          VERSION=$(git tag -l -n1 --format="%(refname:strip=2)" | tail -n1)
          VERSION=$(awk -F. '/[0-9]+\./{$NF++;print}' OFS=. <<< "$VERSION")
          TAG=experimental
          echo "version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        fi
        echo "IMG=ghcr.io/${GITHUB_REPOSITORY,,}:$TAG" >> $GITHUB_ENV
        echo "BUNDLE_IMG=ghcr.io/${GITHUB_REPOSITORY,,}-bundle:$TAG" >> $GITHUB_ENV
        echo "CATALOG_IMG=ghcr.io/${GITHUB_REPOSITORY,,}-catalog:$TAG" >> $GITHUB_ENV
        echo "IMAGE_TAG_BASE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Install operator-sdk
      run: |
        export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
        export OS=$(uname | awk '{print tolower($0)}')
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.26.0
        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
        chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Images
      shell: bash
      run: |
        cd github-arc-operator/
        make docker-build docker-push
        make bundle bundle-build bundle-push catalog-build catalog-push

    - name: Create Release Branch
      run: |
        git checkout -b release-${VERSION}
        git add .
        git commit -am "$VERSION bundle created"
        git push -u origin release-${VERSION}
