name: Check Upstream Chart Version
on: 
  push:
    branches:
      - compare-versions
  workflow_dispatch:

jobs:
  check-local-version:
    name: Check Local Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Helm Install
      uses: azure/setup-helm@v3
    
    - name: Compare Versions
      run: |
        CHART_PATH="simple-arc-operator/helm-charts/actions-runner-controller/Chart.yaml"
        LOCAL_VERSION=$(grep -Po "(?<=version: )(\d+.?){3}" $CHART_PATH)
        
        helm repo add actions-runner-controller \
          https://actions-runner-controller.github.io/actions-runner-controller

        helm repo update

        UPSTREAM_VERSION=$(helm search repo actions-runner-controller -o json | jq -r .[0].version)

        if [ "$LOCAL_VERSION" == "$UPSTREAM_VERSION" ]; then
          echo "Versions match"      
        else
          echo "Versions mismatch regenerate operator"
        fi

        echo "Local:    $LOCAL_VERSION"
        echo "Upstream: $UPSTREAM_VERSION"
