name: Generate Operator
on:
  workflow_call: 

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install operator-sdk
      run: |
        export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
        export OS=$(uname | awk '{print tolower($0)}')
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.26.0
        curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
        chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

    - name: Initialize Operator
      run: |
        rm -rf simple-arc-operator
        mkdir simple-arc-operator
        cd simple-arc-operator
        operator-sdk init \
          --plugins helm \
          --domain boxboat.com \
          --group github-practice \
          --helm-chart actions-runner-controller \
          --helm-chart-repo https://actions-runner-controller.github.io/actions-runner-controller

    - name: Configure Operator Manifests
      run: |
        ./chart-patch.sh
        cat overlays/resource_limits.yaml >> simple-arc-operator/config/manager/kustomization.yaml
        cat overlays/role_permissions.yaml >> simple-arc-operator/config/rbac/kustomization.yaml

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: new-release
        title: Regenerated operator with new chart version

